# 126 Project Traffic Simulator

Let the road be length $n$. Cars start at position 0 and reach their destination at position $n-1$. Each car has an exponential "clock" with parameter $\gamma$, and every time their clock goes off they move forward with probability $p$. If a car is directly in front of them, they do not move regardless. A car enters the road at position 0 at a rate of $Exp(\alpha)$ and exit the road at position $n-1$ with a rate of $Exp(\beta)$. In the 2D Environment, a car has a probability of $z$ of turning at an intersection when its clock goes off.

### Choose global variables:

In [2]:
from ipywidgets import interactive
from IPython.display import display
from IPython.display import clear_output

def set_params(n, alpha, beta, theta, gamma, p, z, seed):
    return [n, alpha, beta, theta, gamma, p, z, seed]

params = interactive(set_params, n=(1, 20), alpha=(0.0, 2.0), beta=(0.0, 2.0), theta=(0.0, 0.5), gamma=(0.0, 2.0), p=(0.0, 1.0), z=(0.0, 1.0), seed=(1, 999))
display(params)

interactive(children=(IntSlider(value=10, description='n', max=20, min=1), FloatSlider(value=1.0, description=…

### Set global variables:
(Note: will break if you set alpha = 0 due to 0 division error)
Remember to rerun this cell every time a slider is updated

In [3]:
n, alpha, beta, theta, gamma, p, z, seed = params.result

### Define particle and environment classes:

In [55]:
import time
import sys
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output


class Particle:
    
    count = 0
    
    def __init__(self, time, gamma=gamma, p=p):
        Particle.count += 1
        self.id = Particle.count - 1
        self.gamma = gamma
        self.p = p
        self._position = 0
        self._time = time # time at which the particle went to this position
        
    def update_position(self, time, value=1):
        self._position += value
        self._time = time # update time
        
    def get_position(self):
        return self._position
        
class Environment:
    def __init__(self, n=n, alpha=alpha, beta=beta):
        self.n = n
        self.alpha = alpha
        self.beta = beta
        self.particles = []
        self.occupied_positions = [0 for _ in range(n)]
        
    def run_simulation(self, time_len=60):
        Particle.count = 0
        curr_time = 0
        actions = []
        entrances = 0
        exits = 0
        travel_times = []
        cell_speeds = []
        num_cars = [0]
        time_of_cars = []
        
        while curr_time < time_len:
            sys.stdout.write("\r{}".format(self.occupied_positions))
            sys.stdout.flush()
            
            merged_param = sum([particle.gamma * particle.p for particle in self.particles]) + self.alpha + self.beta
            time_lapse = np.random.exponential(scale=1/merged_param)
            probabilities = np.array([particle.gamma * particle.p for particle in self.particles] + [self.alpha, self.beta]) / merged_param
            particle = np.random.choice(self.particles + ['entrance', 'exit'], p=probabilities)
            time.sleep(time_lapse)
            curr_time += time_lapse
            if particle == 'entrance':
                if self.occupied_positions[0]:
                    continue
                else:
                    new_particle = Particle(curr_time, gamma=gamma, p=p)
                    self.particles.append(new_particle)
                    self.occupied_positions[0] = 1
                    
                    actions += [(curr_time, new_particle.id, new_particle.get_position())]
                    entrances += 1
                    travel_times.append([curr_time, None])
                    num_cars.append(len(self.particles))
                    time_of_cars.append(curr_time)
                     
            elif particle == 'exit':
                if self.occupied_positions[self.n-1]:
                    end_particle = self.particles.pop(0)
                    self.occupied_positions[self.n-1] = 0
                    
                    actions += [(curr_time, end_particle.id, 'exit')]
                    exits += 1
                    travel_times[end_particle.id][1] = curr_time
                    num_cars.append(len(self.particles))
                    time_of_cars.append(curr_time)
                    
                else:
                    continue
            else:
                particle_pos = particle.get_position()
                if particle_pos == self.n - 1 or self.occupied_positions[particle_pos + 1] == 1: # changed to refer to self.n instead of n
                    continue
                else:
                    self.occupied_positions[particle_pos] = 0
                    self.occupied_positions[particle_pos + 1] = 1
                    
                    cell_speeds.append(1 / (curr_time - particle._time))
                    particle.update_position(curr_time)
                    actions += [(curr_time, particle.id, particle.get_position())]
                    
        print('\n done')
        print('Summary:')
        print('Total entrances: {}'.format(entrances))
        print('Total exits: {}'.format(exits))
        travel_times = [end - begin for begin, end in travel_times if end]
        if len(travel_times) > 0:
            print("Travel times: {}".format([round(t, 2) for t in travel_times]))
            print('Average travel time: {}'.format(sum(travel_times) / len(travel_times)))
        else:
            print('No cars reached the end')
        if len(cell_speeds) > 0:
            print('Average cell speed: {}'.format(sum(cell_speeds) / len(cell_speeds)))
        time_of_cars.append(curr_time)
        t = len(time_of_cars)
        for i in range(1, t):
            time_of_cars[t - i] = time_of_cars[t - i] - time_of_cars[t - i - 1]
        average_num_cars = np.average(num_cars, weights=np.array(time_of_cars) / curr_time)
        print('Average number of cars: {}'.format(round(average_num_cars, 2)))
        
        print('\n Log:')
        for entry in actions:
            print('Time: {}'.format(entry[0]))
            print('Particle: {}'.format(entry[1]))
            print('New position: {}'.format(entry[2]))
            print('\n')

### Add 2D Environment:

In [18]:
class Particle2D(Particle):
    def __init__(self, gamma=gamma, p=p, direction=0, z=z): # 0 is horizontal, 1 is vertical
        Particle.__init__(self, gamma, p)
        self._position = [-1, -1]
        self._direction = direction
        self.z = z
        self.flag = False
        
    def update_position(self, time, value=1):
        self._time = time
        print(self._position)
        self._position[self._direction] += value
        print(self._position)
        
    def set_position(self, value=[-1, -1]):
        self._position = value
        
    def get_direction(self):
        return self._direction
    
    def change_direction(self):
        self._direction = int(not self._direction)
        self.flag = True
        
# FIRST INDEX COLUMN, SECOND INDEX ROAD
class Env2D(Environment):
    def __init__(self, num_roads=(1,1), n=n, alpha=alpha, beta=beta, theta=theta):
        Environment.__init__(self, n, alpha, beta)
        self.theta = theta
        self.occupied_positions = np.array([[0 for _ in range(n)] for _ in range(n)])
        self.horizontal_roads = np.random.choice(range(n), num_roads[0], replace=False)
        self.vertical_roads = np.random.choice(range(n), num_roads[1], replace=False)
        
        self.num_roads = num_roads
        self.intersections = []
        [[self.intersections.append((x, y)) for x in self.vertical_roads] for y in self.horizontal_roads]
        self.inter_directions = {}
        for i in self.intersections:
            self.inter_directions[i] = 0
        
    def run_simulation(self, time_len=60):
        Particle.count = 0
        
#         print(self.occupied_positions)
        
        curr_time = 0
#         time_lapse = np.random.exponential(scale=1/(self.alpha * sum(self.num_roads)))
#         time.sleep(time_lapse)
#         curr_time += time_lapse
#         particle = Particle2D(gamma=gamma, p=p, direction=np.random.choice([0, 1], p=[self.num_roads[0]/sum(self.num_roads), self.num_roads[1]/sum(self.num_roads)]))
#         self.particles.append(particle)
#         if not particle.get_direction():
#             road = np.random.choice(self.horizontal_roads)
#             particle.set_position([0, road])
#             self.occupied_positions[0, road] = 1
#         else:
#             road = np.random.choice(self.vertical_roads)
#             particle.set_position([road, 0])
#             self.occupied_positions[road, 0] = 1
        
        actions = []#[(curr_time, particle.id, particle.get_position())]
        entrances = 0#1
        exits = 0
        travel_times = []
        cell_speeds = []
        num_cars = [0]
        time_of_cars = []
        
        while curr_time < time_len:
            clear_output(wait=True)
            print(self.occupied_positions)
            
            merged_param = sum([particle.gamma * particle.p for particle in self.particles]) + (self.alpha + self.beta) * sum(self.num_roads) + self.theta * (sum(self.num_roads) ** 2)  
            time_lapse = np.random.exponential(scale=1/merged_param)
            probabilities = np.array([particle.gamma * particle.p for particle in self.particles] + [self.alpha for _ in range(sum(self.num_roads))] + [self.beta for _ in range(sum(self.num_roads))] + [self.theta for _ in range(sum(self.num_roads) ** 2)]) / merged_param
            particle = np.random.choice(self.particles + ['entrance' for _ in range(sum(self.num_roads))] + ['exit' for _ in range(sum(self.num_roads))] + ['intersection' for _ in range(sum(self.num_roads) ** 2)], p=probabilities)
            time.sleep(time_lapse)
            curr_time += time_lapse
            if particle == 'entrance':
                direction = np.random.choice([0, 1], p=[len(self.horizontal_roads)/sum(self.num_roads), len(self.vertical_roads)/sum(self.num_roads)])
                if not direction:
                    road = np.random.choice(self.horizontal_roads)
                    if self.occupied_positions[0][road]:
                        continue
                    new_particle = Particle2D(gamma=gamma, p=p, direction=direction)
                    self.particles.append(new_particle)
                    self.occupied_positions[0][road] = 1
                    new_particle.set_position([0, road])
                else:
                    road = np.random.choice(self.vertical_roads)
                    if self.occupied_positions[road][0]:
                        continue
                    new_particle = Particle2D(gamma=gamma, p=p, direction=direction)
                    self.particles.append(new_particle)
                    self.occupied_positions[road][0] = 1
                    new_particle.set_position([road, 0])
                
                travel_times.append([curr_time, None])
                actions += [(curr_time, new_particle.id, new_particle.get_position())]
                entrances += 1
                num_cars.append(len(self.particles))
                time_of_cars.append(curr_time)
                    
            elif particle == 'exit':
                direction = np.random.choice([0, 1], p=[len(self.horizontal_roads)/sum(self.num_roads), len(self.vertical_roads)/sum(self.num_roads)])
                if not direction:
                    road = np.random.choice(self.horizontal_roads)
                    if self.occupied_positions[self.n-1][road]:
                        particle = [p for p in self.particles if p.get_position() == [self.n-1, road]][0]
                        self.particles.remove(particle)
                        self.occupied_positions[self.n-1][road] = 0
                        actions += [(curr_time, particle.id, [n, road])]
                        exits += 1
                        travel_times[particle.id][1] = curr_time
                        num_cars.append(len(self.particles))
                        time_of_cars.append(curr_time)
                else:
                    road = np.random.choice(self.vertical_roads)
                    if self.occupied_positions[road][self.n-1]:
                        particle = [p for p in self.particles if p.get_position() == [road, self.n-1]][0]
                        self.particles.remove(particle)
                        self.occupied_positions[road][self.n-1] = 0
                        actions += [(curr_time, particle.id, [road, n])]
                        exits += 1
                        travel_times[particle.id][1] = curr_time
                        num_cars.append(len(self.particles))
                        time_of_cars.append(curr_time)
            elif particle == 'intersection':
                i = np.random.choice(range(len(self.intersections)))
                intersection = self.intersections[i]
                self.inter_directions[intersection] = 0 if self.inter_directions[intersection] else 1
                actions += [(curr_time, 'intersection' + str(intersection), self.inter_directions[intersection])] 
            else:
                particle_pos = particle.get_position()
                direction = particle.get_direction()
                if not particle.flag and any([particle_pos[0] == i[0] and particle_pos[1] == i[1] for i in self.intersections]):
                    rand = np.random.random()
                    if rand < particle.z:
                        particle.change_direction()
                if not direction:
                    pos = (particle_pos[0] + 1, particle_pos[1])
                    if any([pos[0] == i[0] and pos[1] == i[1] for i in self.intersections]) and self.inter_directions[tuple(pos)]:
                        continue
                    elif particle_pos[0] >= self.n - 1 or self.occupied_positions[particle_pos[0] + 1, particle_pos[1]] == 1:
                        continue
                    else:
                        cell_speeds.append(1 / (curr_time - particle._time))
                        self.occupied_positions[particle_pos[0]][particle_pos[1]] = 0
                        self.occupied_positions[particle_pos[0] + 1][particle_pos[1]] = 1
                        particle.update_position(curr_time)
                        actions += [(curr_time, particle.id, particle.get_position())]
                        particle.flag = False
                else:
                    pos = (particle_pos[0], particle_pos[1] + 1)
                    if any([pos[0] == i[0] and pos[1] == i[1] for i in self.intersections]) and not self.inter_directions[tuple(pos)]:
                        continue
                    elif particle_pos[1] >= self.n - 1 or self.occupied_positions[particle_pos[0], particle_pos[1] + 1] == 1:
                        continue
                    else:
                        cell_speeds.append(1 / (curr_time - particle._time))
                        self.occupied_positions[particle_pos[0]][particle_pos[1]] = 0
                        self.occupied_positions[particle_pos[0]][particle_pos[1] + 1] = 1
                        particle.update_position(curr_time)
                        actions += [(curr_time, particle.id, particle.get_position())]
                        particle.flag = False
                    
        print('\n done')
        print('Summary:')
        print('Total entrances: {}'.format(entrances))
        print('Total exits: {}'.format(exits))
        travel_times = [end - begin for begin, end in travel_times if end]
        if len(travel_times) > 0:
#             print("Travel times: {}".format([round(t, 2) for t in travel_times]))
            print('Average travel time: {} seconds'.format(round(sum(travel_times) / len(travel_times), 3)))
        else:
            print('No cars reached the end')
        if len(cell_speeds) > 0:
            print('Average cell speed: {} cells per second'.format(round(sum(cell_speeds) / len(cell_speeds), 3)))
        time_of_cars.append(curr_time)
        t = len(time_of_cars)
        for i in range(1, t):
            time_of_cars[t - i] = time_of_cars[t - i] - time_of_cars[t - i - 1]
        average_num_cars = np.average(num_cars, weights=np.array(time_of_cars) / curr_time)
        print('Average number of cars: {}'.format(round(average_num_cars, 2)))
        print('\n Log:')
        for entry in actions:
            print('Time: {}'.format(entry[0]))
            print('Particle: {}'.format(entry[1]))
            print('New position: {}'.format(entry[2]))
            print('\n')

### Multiple Lanes Environment:

In [47]:
class ParticleManyLane(Particle):
    def __init__(self, time, lane, gamma=gamma, p=p):
        Particle.__init__(self, time, gamma, p)
        self._position = [lane, 0] #first index lane, second index position
        
    def update_position(self, time, value=(0, 1)):
        self._time = time
        self._position[0] += value[0]
        self._position[1] += value[1]
        
    def set_position(self, value=[-1, -1]):
        self._position = value
        
    def get_position(self):
        return self._position[0], self._position[1]
    
class EnvManyLane(Environment):
    def __init__(self, n=n, alpha=alpha, beta=beta, lanes=1, delta=0.5):
        Environment.__init__(self, n, alpha, beta)
        self.lanes = lanes
        self.occupied_positions = np.zeros((lanes, n))
        self.delta = delta # tendency to change lanes
        #first index lane, second index position
        
    def run_simulation(self, time_len=60):
        Particle.count = 0 
        curr_time = 0
        entrances = 0
        exits = 0
        actions = []
        travel_times = []
        cell_speeds = []
        num_cars = [[0] for _ in range(self.lanes)]
        time_of_cars = [[] for _ in range(self.lanes)]
        
        while curr_time < time_len:
            clear_output(wait=True)
            print(self.occupied_positions)
            
            merged_param = sum([particle.gamma * particle.p for particle in self.particles]) + self.lanes * self.alpha + self.lanes * self.beta
            time_lapse = np.random.exponential(scale=1/merged_param)
            probabilities = np.array([particle.gamma * particle.p for particle in self.particles] +  [self.lanes * self.alpha, self.lanes * self.beta]) / merged_param
            particle = np.random.choice(self.particles + ['entrance', 'exit'], p=probabilities)
            time.sleep(time_lapse)
            curr_time += time_lapse
            if particle == 'entrance':
                lane = np.random.randint(0, self.lanes)
                if self.occupied_positions[lane, 0]:
                    continue
                else:
                    new_particle = ParticleManyLane(curr_time, lane, gamma=gamma, p=p)
                    self.particles.append(new_particle)
                    self.occupied_positions[lane, 0] = 1
                    
                    actions += [(curr_time, new_particle.id, new_particle.get_position())]
                    entrances += 1
                    travel_times.append([curr_time, None])
                    num_cars[lane].append(np.sum(self.occupied_positions[lane, :]))
                    time_of_cars[lane].append(curr_time)
                    
            elif particle == 'exit':
                lane = np.random.randint(0, self.lanes)
                if self.occupied_positions[lane, self.n-1]: 
                    for i in range(len(self.particles)):
                        particle = self.particles[i]
                        if particle.get_position() == (lane, self.n-1):
                            end_particle = particle
                            self.particles.pop(i)
                            break
                    self.occupied_positions[lane, self.n-1] = 0 
                    
                    actions += [(curr_time, end_particle.id, 'exit')]
                    exits += 1
                    travel_times[end_particle.id][1] = curr_time
                    num_cars[lane].append(np.sum(self.occupied_positions[lane, :]))
                    time_of_cars[lane].append(curr_time)
                    
                else:
                    continue
            else:
                particle_lane, particle_pos = particle.get_position()
                options = []
                if particle_pos != self.n - 1 and self.occupied_positions[particle_lane, particle_pos + 1] != 1:
                    options.append((0, 1)) # advance
                if particle_lane - 1 >= 0 and self.occupied_positions[particle_lane - 1, particle_pos - 1] == 0 and self.occupied_positions[particle_lane - 1, particle_pos] == 0:
                    options.append((-1, 0)) # left
                if particle_lane + 1 < self.lanes and self.occupied_positions[particle_lane + 1, particle_pos - 1] == 0 and self.occupied_positions[particle_lane + 1, particle_pos] == 0:
                    options.append((1, 0)) # right
                    
                if len(options) == 0:
                    continue
                else:
                    probabilities = []
                    # see which options are available and pick with probability proportional to the number of open spaces
                    # proportional to number of cars in front
                    if (0, 1) in options:
                        probabilities.append((self.n - np.sum(self.occupied_positions[particle_lane, particle_pos:])) * (1 - self.delta))
                    if (-1, 0) in options:
                        probabilities.append((self.n - np.sum(self.occupied_positions[particle_lane - 1, particle_pos:])) * self.delta)
                    if (1, 0) in options:
                        probabilities.append((self.n - np.sum(self.occupied_positions[particle_lane + 1, particle_pos:])) * self.delta)
                    probabilities = probabilities / sum(probabilities)
                    # choose option and update model
                    option = options[np.random.choice(len(options), p=probabilities)]
                    self.occupied_positions[particle_lane, particle_pos] = 0
                    self.occupied_positions[particle_lane + option[0], particle_pos + option[1]] = 1
                    if option == (0, 1):
                        cell_speeds.append(1 / (curr_time - particle._time))
                        particle.update_position(curr_time, (0, 1))
                    else:
                        num_cars[particle_lane].append(num_cars[particle_lane][-1] - 1)
                        time_of_cars[particle_lane].append(curr_time)
                        particle.update_position(particle._time, (option))
                        particle_lane, particle_pos = particle.get_position()
                        num_cars[particle_lane].append(num_cars[particle_lane][-1] + 1)
                        time_of_cars[particle_lane].append(curr_time)
                        
                    actions += [(curr_time, particle.id, particle.get_position())]
                          
        print('\n done')
        print('Summary:')
        print('Total entrances: {}'.format(entrances))
        print('Total exits: {}'.format(exits))
        travel_times = [end - begin for begin, end in travel_times if end]
        if len(travel_times) > 0:
#             print("Travel times: {}".format([round(t, 2) for t in travel_times]))
            print('Average travel time: {} seconds'.format(round(sum(travel_times) / len(travel_times), 3)))
        else:
            print('No cars reached the end')
        if len(cell_speeds) > 0:
            print('Average cell speed: {} cells per second'.format(round(sum(cell_speeds) / len(cell_speeds), 3)))
        for lane in time_of_cars:
            lane.append(curr_time)
        
        for lane in time_of_cars:
            t = len(lane)
            for i in range(1, t):
                lane[t - i] = lane[t - i] - lane[t - i - 1]
        average_num_cars = [np.average(n, weights=np.array(ti) / curr_time) for n, ti in zip(num_cars, time_of_cars)]
        average_num_cars = list(map(lambda x: round(x, 2), average_num_cars))
        print('Average number of cars in each lane: {}'.format(average_num_cars))
        print('\n Log:')
        for entry in actions:
            print('Time: {}'.format(round(entry[0], 2)), end = " ")
            print('Particle: {}'.format(entry[1]), end = " ")
            print('New lane, position: ({},{})'.format(entry[2][0], entry[2][1]), end = " ")
            print('\n')

### Run simulator:

In [56]:
env1 = Environment(n=n, alpha=alpha, beta=beta)
env1.run_simulation(time_len = 10)

[1, 1, 0, 0, 1, 0, 0, 0, 1, 0]
 done
Summary:
Total entrances: 4
Total exits: 0
No cars reached the end
Average cell speed: 1.590037842091649
Average number of cars: 3.05

 Log:
Time: 0.29143729644154853
Particle: 0
New position: 0


Time: 0.624086870144491
Particle: 0
New position: 1


Time: 1.6885776505758452
Particle: 0
New position: 2


Time: 1.7077024235325018
Particle: 1
New position: 0


Time: 2.2422846568758907
Particle: 1
New position: 1


Time: 2.5044310435562487
Particle: 0
New position: 3


Time: 2.7647478113439448
Particle: 2
New position: 0


Time: 2.914270691804814
Particle: 1
New position: 2


Time: 4.696471238141572
Particle: 2
New position: 1


Time: 5.20470703228836
Particle: 3
New position: 0


Time: 5.718556682123593
Particle: 0
New position: 4


Time: 5.971323464725216
Particle: 0
New position: 5


Time: 6.172967390498126
Particle: 0
New position: 6


Time: 7.793200691055196
Particle: 0
New position: 7


Time: 8.732104519949846
Particle: 1
New position: 3


Time: 

In [57]:
env = Env2D(num_roads=(1, 1), n=n, alpha=alpha, beta=beta, theta=theta)
env.run_simulation(time_len = 10)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

 done
Summary:
Total entrances: 3
Total exits: 0
No cars reached the end
Average cell speed: 6.505 cells per second
Average number of cars: 2.2

 Log:
Time: 0.3650707598818904
Particle: 0
New position: [3, 8]


Time: 1.7175221206357423
Particle: intersection(6, 8)
New position: 1


Time: 2.0587719937666806
Particle: 1
New position: [6, 0]


Time: 2.162564404927156
Particle: intersection(6, 8)
New position: 0


Time: 4.830841603201216
Particle: 0
New position: [3, 8]


Time: 4.871766070529996
Particle: 0
New position: [3, 8]


Time: 5.578549841632102
Particle: 2
New position: [1, 8]


Time: 5.709015497823292
Particle: 0
New position: [3, 8]


Time: 7.873905126316281
Particle: intersection(6, 8)
New position: 1


Time: 7.880052035385071
Particle: intersection(

In [48]:
env2 = EnvManyLane(n=n, alpha=alpha, beta=beta, lanes=2)
env2.run_simulation(time_len = 10)

[[1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 0. 0. 0. 0. 0.]]

 done
Summary:
Total entrances: 5
Total exits: 0
No cars reached the end
Average cell speed: 1.156 cells per second
Average number of cars: [1.48, 1.32]

 Log:
Time: 0.98 Particle: 0 New lane, position: (0,0) 

Time: 2.07 Particle: 1 New lane, position: (1,0) 

Time: 3.51 Particle: 0 New lane, position: (0,1) 

Time: 3.7 Particle: 2 New lane, position: (0,0) 

Time: 4.85 Particle: 1 New lane, position: (1,1) 

Time: 5.14 Particle: 1 New lane, position: (1,2) 

Time: 5.48 Particle: 2 New lane, position: (1,0) 

Time: 5.99 Particle: 3 New lane, position: (0,0) 

Time: 7.79 Particle: 0 New lane, position: (0,2) 

Time: 8.1 Particle: 3 New lane, position: (0,1) 

Time: 8.2 Particle: 0 New lane, position: (0,3) 

Time: 8.71 Particle: 3 New lane, position: (0,2) 

Time: 8.8 Particle: 1 New lane, position: (1,3) 

Time: 9.35 Particle: 3 New lane, position: (1,2) 

Time: 9.4 Particle: 4 New lane, position: (0,0) 

